# Generated by Django 3.2 on 2025-04-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20250403_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
